(
~sample_sets = [
  IdentityDictionary[ // 0
    \drum_0 -> \Kick1,
    \drum_1 -> \Kick2,
    \drum_2 -> \Snare1,
    \drum_3 -> \Clap1,
    \drum_4 -> \Whip,
    \drum_5 -> \Hat1,
    \drum_6 -> \Hat2,
    \drum_7 -> \Cymbal1
  ],
  IdentityDictionary[ // 1
    \drum_0 -> \Kick3,
    \drum_1 -> \Kick4,
    \drum_2 -> \Clap2,
    \drum_3 -> \Snap1,
    \drum_4 -> \Whip,
    \drum_5 -> \Snare1,
    \drum_6 -> \Hat3,
    \drum_7 -> \Cymbal1
  ]
];
)