~chordSets = IdentityDictionary[
  \bion1 -> [
    (voicing: \Xm, pitchClass: PC(\bf, 3)),
    (voicing: \XM, pitchClass: PC(\af, 3)),
    (voicing: \XM, pitchClass: PC(\gf, 3)),
    (voicing: \XM, pitchClass: PC(\f, 3)),

    (voicing: \X7, pitchClass: PC(\ef, 4))
  ],
  \bion2 -> [
    (voicing: \Xm11, pitchClass: PC(\f, 4)),
    (voicing: \Xm7, pitchClass: PC(\c, 5)),
    (voicing: \X7, pitchClass: PC(\bf, 5)),
    (voicing: \XM, pitchClass: PC(\c, 4))
  ]
];
