IdentityDictionary[
  // name, loopable, beatSynced
  \bion2 -> [
    [ "bion_2_1",              false, true ],
    [ "bion_2_2",              false, true ],
    [ "bion_2_3",              false, true ]
  ],
  \jon1 -> [
    [ "HER1JONSample1",        false, true ],
    [ "HER1JONSample1wPickup", false, true  ],
    [ "HER1JONSample2",        false, true  ],
    [ "HER1JONSample3",        true,  true  ],
    [ "HER1JONSample4",        false, true]
  ]
];
