#!/bin/bash -e

OUTPUT_DIR_NAME=~/Desktop/rehearsal_multitracks_$(date +"%m-%d-%y")

printf "\narchiving rehearsal recordings to $OUTPUT_DIR_NAME...\n\n"

for session_dir in ./recordings/*
do
    session_output_dir="$OUTPUT_DIR_NAME/$(basename $session_dir)"
    mkdir -p $session_output_dir

    printf "copying drum archive file if present..."
    if [ -f "$session_dir/drums" ]; then
        cp "$session_dir/drums" "$session_output_dir/drums"
    fi
    printf "done\n"

    IFS=$(printf "\n\b")
    find $session_dir -iname "*.aiff" -print0 |
    while read -d $'\0' file
    do
        name=$(basename -s .aiff $file | sed 's/ /_/g')
        printf "converting "$name"..."
        sox $file "$session_output_dir/$name.flac"
        printf " done\n"
    done
    printf "finished converting $session_dir\n\n"
done

printf "\ncompressing converted files...\n"

tar -zcvf "$OUTPUT_DIR_NAME.tar.gz" -C $OUTPUT_DIR_NAME .

printf "done compressing\n\n"
printf "archive is at: "$OUTPUT_DIR_NAME"\n"

# printf "wiping recording directory and cleaning up... "
printf "cleaning up... "

# rm recordings/*.aiff
rm -r $OUTPUT_DIR_NAME

printf "done\n"

printf "\nall done!\n"
